### ISSUE TITLE
Latest event appears first in upcoming events

### ISSUE THREAD

**Issue by artfuldev** [sahajsoft/devday#102]

**Comment by Deepthi-Chand** [comment]
Shouldn't be that way. i.e the event closer to current date be on top?

**Comment by artfuldev** [comment]
It wasn't being shown in that way, and that was the bug.
"Latest" means "most late". In order to show the closest event first, the "latest" event should be shown last.

**Comment by Deepthi-Chand** [comment]
Check devday.in ... Its still showing the "latest"  event first. Nov 16 is first and oct 28 next.

**Comment by artfuldev** [comment]
Hard refresh? Maybe your version is cached?

**Comment by artfuldev** [comment]
If it's showing the incorrect order for you, perhaps it's a deeper bug that needs a better fix. Feel free to reopen this issue if that is the case. We'll figure it out.

**Comment by Deepthi-Chand** [comment]
Looks like it.. same behavior in chrome and firefox... Expected behavior in safari. Reopening,.

**Comment by Deepthi-Chand** [comment]
Working fine now..

**Comment by artfuldev** [comment]
Good that you noticed in time.
