### ISSUE TITLE
Home page should never be stale.

### ISSUE THREAD

**Issue by sriki77** [sahajsoft/devday#4]
Home page of dev day should never be stale.
1. If we have agenda for next month - that will be on the page.
2. If not we should have summary of the activities done till now and let people read about it.

**Comment by artfuldev** [comment]
We will also have twitter feed of @devday_ for people to see, I think that would also help keep the home page from getting stale, as long as we stream new content via twitter often enough.

**Comment by artfuldev** [comment]
We are planning to have the next 2 upcoming events (one in Chennai and one in Banaglore) displayed on the homepage. The events displayed will be like cards, leading to a full-blown event page. Please share your thoughts. For a sneak-peek please have a look at https://artfuldev.github.io/devday/ which is in development.

**Comment by artfuldev** [comment]
The "More ->" link below the next 2 upcoming events will lead to the archive page, which will have all previous events listed as cards, each one will have a link to the event detail page. All this can be seen in the dev site link I shared above. Please share your thoughts.

**Comment by artfuldev** [comment]
I think this is mostly done for now. What do you think, @sriki77 ?
If you think we have done this, you can go ahead and close this issue. If not, let's add more details here and take this to completion.

**Comment by artfuldev** [comment]
Closing as done. @sriki77 can reopen this if required.
