### ISSUE TITLE
Allow deep linking to a particular event

### ISSUE THREAD

**Issue by arvsr1988** [sahajsoft/devday#40]
<a href="https://github.com/artfuldev"><img src="https://avatars.githubusercontent.com/u/3091087?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artfuldev](https://github.com/artfuldev)**
_Sunday Aug 07, 2016 at 07:18 GMT_
_Originally opened as https://github.com/artfuldev/devday/issues/29_

---

The ideal way is to animate to it from the home page

**Comment by artfuldev** [comment]
Fixed in #68
