### ISSUE TITLE
Allow deep linking to registering for a particular upcoming event

### ISSUE THREAD

**Issue by arvsr1988** [sahajsoft/devday#41]
<a href="https://github.com/artfuldev"><img src="https://avatars.githubusercontent.com/u/3091087?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artfuldev](https://github.com/artfuldev)**
_Sunday Aug 07, 2016 at 07:19 GMT_
_Originally opened as https://github.com/artfuldev/devday/issues/30_

---

**Comment by artfuldev** [comment]
Does not work with the latest design. Deep linking to the event itself opens a page which has the registration form
