### ISSUE TITLE
Rethink archive events design

### ISSUE THREAD

**Issue by arvsr1988** [sahajsoft/devday#49]
<a href="https://github.com/artfuldev"><img src="https://avatars.githubusercontent.com/u/3091087?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [artfuldev](https://github.com/artfuldev)**
_Sunday Aug 14, 2016 at 04:10 GMT_
_Originally opened as https://github.com/artfuldev/devday/issues/42_

---

Thoughts from Prem include distraction due to multiple events close together

**Comment by artfuldev** [comment]
Thinking of adding a new page for this, might work out better than we think.
